esphome:
  name: analyse_trames_ac

esp8266:
  board: d1_mini

logger:
  level: DEBUG


wifi:
  ssid: "wifi_becheau"
  password: "wifibecheau12denisy"

# Pour voir les logs OTA
api:
  password: "motdepasse_api"
ota:
  platform: esphome
  password: "MonMotDePasseOTA"

web_server:
  port: 80
  auth:
    username: admin
    password: admin
  version: 3
  log: true
  local : true
  include_internal: true

# uart:
#   id: uart_log
#   tx_pin:
#     number: GPIO1
#     inverted: true #active with octo
#   rx_pin:
#     number: GPIO3
#     inverted: true #active with octo
#   baud_rate: 9600  # ou 115200 si nécessaire
#   debug:
#     direction: RX
#     dummy_receiver: true