substitutions:
  dev_name: acw02-salon
  dev_friendly: ACW02 salon
  lang: "fr"

  board: d1_mini
  

esphome:
  name: ${dev_name}
  friendly_name: ${dev_friendly}
  platformio_options:
    build_flags:
      - -DDLOCALE_LANG=\"${lang}\"
      - -DDBOARD=\"${board}\"

esp8266:
  board: ${board}
  framework:
    platform_version: 4.0.1
  


  
logger:
  level: INFO
  


external_components:
  - source:
      type: local
      path: components
    components: [acw02]

binary_sensor:
  name: test
  platform: template
  
acw02:
  name: Empty switch
